name: Deploy Next.js App with Bun

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'  # Only trigger on changes in app/web folder
      - '.github/workflows/deploy-prod-web.yml'  # Only trigger on changes in app/web folder

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest  # or specify a version

      - name: Install dependencies
        working-directory: ./apps/web
        run: bun install

      - name: Build Next.js app
        working-directory: ./apps/web
        run: bun run build

      - name: copy build to server 
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: apps/web/.next apps/web/public apps/web/package.json
          remote_path: /root/pulpmovies/web
          remote_host: ${{ secrets.SERVER_IP }} 
          remote_user: ${{ secrets.SERVER_USER }} 
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: multiple command
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export BUN_INSTALL="$HOME/.bun"
            export PATH=$BUN_INSTALL/bin:$PATH
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            source ~/.bashrc
            cd /root/pulpmovies/web 
            bun install --production

            pm2 restart /root/pulpmovies/ecosystem.config.js --only web

